name: compile and check hash
on:
  issues:
    types: [opened]

jobs:
  build-and-verify:
    if: contains(github.event.issue.labels.*.name, 'run')
    runs-on: ubuntu-latest
    steps:
    - name: parse issue body for inputs  
      id: parse
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
      run: |
        echo "REPO_NAME=$(echo '${{ github.event.issue.body }}' | jq -r '.repo_name')" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(echo '${{ github.event.issue.body }}' | jq -r '.commit_hash')" >> $GITHUB_ENV
        echo "REF_HASH=$(echo '${{ github.event.issue.body }}' | jq -r '.ref_hash')" >> $GITHUB_ENV
        echo "DOCKER_IMAGE=$(echo '${{ github.event.issue.body }}' | jq -r '.docker_image')" >> $GITHUB_ENV
        echo "WORKING_DIR=$(echo '${{ github.event.issue.body }}' | jq -r '.working_dir')" >> $GITHUB_ENV
  
    - name: checkout specific commit of the repository
      uses: actions/checkout@v3
      with:
        repository: ${{ env.REPO_NAME }}
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ env.COMMIT_HASH }} 
        path: 'repo'
    
    - name: add status label
      if: success()
      run: gh issue edit "$NUMBER" --add-label "$LABELS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: 'in progress'

    - name: compile code with docker
      run: |
        docker run --rm -v "$GITHUB_WORKSPACE/repo/${{ env.WORKING_DIR }}":/code \
          --mount type=volume,source=code_cache_${{ env.RUNNER_TRACKING_ID }},target=/target \
          --mount type=volume,source=registry_cache_${{ env.RUNNER_TRACKING_ID }},target=/usr/local/cargo/registry \
          ${{ env.DOCKER_IMAGE }}

    - name: Check if input hash is in checksums.txt
      id: checksum_check
      run: |
        CHECKSUM_FILE="$GITHUB_WORKSPACE/repo/${{ env.WORKING_DIR }}/artifacts/checksums.txt"
        if grep -q "$(echo '${{ env.REF_HASH }}' | tr '[:upper:]' '[:lower:]')" "$CHECKSUM_FILE"; then
          echo "Reference hash found in checksums.txt"
        else
          echo "Reference hash not found in checksums.txt"
          echo "CHECKSUM_NOT_FOUND=true" >> $GITHUB_ENV
          exit 78
        fi

    - name: remove status label
      if: always()
      run: gh issue edit "$NUMBER" --remove-label "$LABELS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: 'in progress'
  
    - name: add matched label
      if: success()
      run: gh issue edit "$NUMBER" --add-label "$LABELS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: 'matched'

    - name: add failed label
      if: failure() && steps.checksum_check.outputs.CHECKSUM_NOT_FOUND != 'true'
      run: gh issue edit "$NUMBER" --add-label "$LABELS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: 'run failed'

    - name: add not matched label
      if: env.CHECKSUM_NOT_FOUND == 'true'
      run: gh issue edit "$NUMBER" --add-label "$LABELS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        LABELS: 'not matched'
